### ISSUE TITLE
Linux issue (and suggestion)

### ISSUE THREAD

**Issue by GummyJon1** [Shugabuga/Splatoon2RichPresence#4]
Hey, just downloaded this RPC client. It works great so far on Linux, though there's one issue. I am unable to resize the window, and not all of the text fits in. 
![image](https://user-images.githubusercontent.com/19827426/43492486-9cbf37ac-94ff-11e8-8569-7e4199d06c30.png)
Also my suggestion is a private battle mode so people can know if you're playing a PB (maybe an option to put the password up as well)
Other than that, nice program!

**Comment by Shugabuga** [comment]
Thanks for letting me know about the Linux support! It seems only Windows doesn't work.

---

For that visual bug, I recommend you to install the given fonts, but I'll enable resizing.

---

For that suggestion, I'll keep it in mind.
