### ISSUE TITLE
RPC connection failed on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by hagretek** [Shugabuga/Splatoon2RichPresence#5]
I tried running this script like normal, but I get this error message upon opening:

```sh
RPC connection failed! Is Discord open?
```

I tried restarting both Discord, both the script but it just kept on giving me this error.

I'm using **Ubuntu 18.04.1 Bionic Beaver LTS**. And yes, Discord is open.

**Comment by Shugabuga** [comment]
Why did you close this issue? Can you post resolution instructions if you found a solution?
